var textToDecode = 'W3siaWQiOjQxLCJzIjoibGxvd2luZyBjbyJ9LHsiaWQiOjksInMiOiJuZyBzaXRlcy4gIn0seyJpZCI6MCwicyI6IkR1ZSB0byBhIG0ifSx7ImlkIjoxOSwicyI6IiBtb3N0IHN1aXQifSx7ImlkIjoxOCwicyI6InQgZml2ZSB0aGUifSx7ImlkIjoxMCwicyI6IllvdSBuZWVkIHQifSx7ImlkIjo3MCwicyI6ImF0aW9ucyBmb3IifSx7ImlkIjo2MCwicyI6ImUgKC05MC4uLjkifSx7ImlkIjoyMiwicyI6IiBvbiB0aGUgZm8ifSx7ImlkIjozNSwicyI6ImUgKHRoZSBsYXIifSx7ImlkIjoyLCJzIjoiIGluIHRoZSBuYSJ9LHsiaWQiOjI3LCJzIjoiIHNtYWxsZXIgdCJ9LHsiaWQiOjcsInMiOiIgYW5kIHNlY29uIn0seyJpZCI6NjEsInMiOiIwKTtBcmVhIFNpIn0seyJpZCI6NjIsInMiOiJ6ZSAoc3Eua20uIn0seyJpZCI6NDYsInMiOiJlZiAtIDEwMCUsIn0seyJpZCI6NTMsInMiOiJwcmVzZW50ZWQgIn0seyJpZCI6MzksInMiOiIgY3JpdGVyaWEgIn0seyJpZCI6NTIsInMiOiJ0aW9ucyBhcmUgIn0seyJpZCI6NjYsInMiOiJlbGVjdCBmaXZlIn0seyJpZCI6MzIsInMiOiJlciB0byAwIHRoIn0seyJpZCI6MjQsInMiOiJpdGVyaWE6XG5cbi0ifSx7ImlkIjoxMiwicyI6InRoZXIgbGFuZGkifSx7ImlkIjo4LCJzIjoiZGFyeSBsYW5kaSJ9LHsiaWQiOjM0LCJzIjoiLSBBcmVhIFNpeiJ9LHsiaWQiOjUxLCJzIjoiYWlsYWJsZSBvcCJ9LHsiaWQiOjExLCJzIjoibyBmaW5kIGFubyJ9LHsiaWQiOjU2LCJzIjoibWF0OiBcbklEO1MifSx7ImlkIjo1LCJzIjoiIHNoaXAgbWlzcyJ9LHsiaWQiOjMwLCJzIjoiLSBMYXRpdHVkZSJ9LHsiaWQiOjQzLCJzIjoiIG9mIHNpZ25pZiJ9LHsiaWQiOjMxLCJzIjoiICh0aGUgY2xvcyJ9LHsiaWQiOjE1LCJzIjoicmUgYXJlIG11bCJ9LHsiaWQiOjUwLCJzIjoiNSVcblxuVGhlIGF2In0seyJpZCI6MzgsInMiOiJoIG9mIHRoZXNlIn0seyJpZCI6NzEsInMiOiIgdGhlIHNoaXAuIn0seyJpZCI6NTcsInMiOiJ1cmZhY2UgUmVsIn0seyJpZCI6NjksInMiOiJhbmRpbmcgbG9jIn0seyJpZCI6MjAsInMiOiJhYmxlIGxvY2F0In0seyJpZCI6MTMsInMiOiJuZyBsb2NhdGlvIn0seyJpZCI6MjksInMiOiJlIGJldHRlcilcbiJ9LHsiaWQiOjE0LCJzIjoibiwgYnV0IHRoZSJ9LHsiaWQiOjY1LCJzIjoib2dyYW0gdG8gcyJ9LHsiaWQiOjQ5LCJzIjoiYSBTaXplIC0gMiJ9LHsiaWQiOjI2LCJzIjoiZWxpZWYgKHRoZSJ9LHsiaWQiOjU0LCJzIjoiaW4gdGhlIGZvbCJ9LHsiaWQiOjQyLCJzIjoiZWZmaWNpZW50cyJ9LHsiaWQiOjE3LCJzIjoib25zLiBTZWxlYyJ9LHsiaWQiOjQwLCJzIjoiaGFzIHRoZSBmbyJ9LHsiaWQiOjEsInMiOiJhbGZ1bmN0aW9uIn0seyJpZCI6NDgsInMiOiItIDUwJSwgQXJlIn0seyJpZCI6MTYsInMiOiJ0aXBsZSBvcHRpIn0seyJpZCI6NTgsInMiOiJpZWYgKDAuLi4xIn0seyJpZCI6MjgsInMiOiJoZSByYXRlIHRoIn0seyJpZCI6NTksInMiOiIwKTtMYXRpdHVkIn0seyJpZCI6MzcsInMiOiJ0dGVyKVxuXG5FYWMifSx7ImlkIjo2MywicyI6IilcblxuUGxlYXNlICJ9LHsiaWQiOjIzLCJzIjoibGxvd2luZyBjciJ9LHsiaWQiOjMzLCJzIjoiZSBiZXR0ZXIpXG4ifSx7ImlkIjoyMSwicyI6ImlvbnMgYmFzZWQifSx7ImlkIjoyNSwicyI6IiBTdXJmYWNlIFIifSx7ImlkIjo0LCJzIjoieXN0ZW0sIHRoZSJ9LHsiaWQiOjMsInMiOiJ2aWdhdGlvbiBzIn0seyJpZCI6NDcsInMiOiIgTGF0aXR1ZGUgIn0seyJpZCI6NDUsInMiOiJyZmFjZSBSZWxpIn0seyJpZCI6NDQsInMiOiJpY2FuY2U6XG5TdSJ9LHsiaWQiOjY4LCJzIjoicG9zc2libGUgbCJ9LHsiaWQiOjY3LCJzIjoiIHRoZSBiZXN0ICJ9LHsiaWQiOjM2LCJzIjoiZ2VyIHRoZSBiZSJ9LHsiaWQiOjU1LCJzIjoibG93aW5nIGZvciJ9LHsiaWQiOjY0LCJzIjoid3JpdGUgYSBwciJ9LHsiaWQiOjYsInMiOiJlZCBwcmltYXJ5In1d';
var decodedText = JSON.parse(new Buffer(textToDecode, 'base64').toString('utf8'));
var md5 = require('md5');

function sortObj(i, ii) {
    if (i['id'] > ii['id'])
        return 1;
    else if (i['id'] < ii['id'])
        return -1;
    else
        return 0;
}

decodedText.sort(sortObj);
var text = '';
for (const key in decodedText) {
    if (decodedText.hasOwnProperty(key)) {
        text = text + decodedText[key]['s'];        
    }
}

var result = md5(text);
console.log('​text', text);
console.log('​result', result);